# -----------  Agents  -----------
[[agents]]
  id = "test_agent1"
  name = "Agent 1"
  public_address = "HcScJtQkeJ4hkdqtxrdgh8jPybRynkaxmCSFZxKG6Nsf3tei6zRAnEdy97Qzeua"
  keystore_file = "./agent1.key"
[[agents]]
  id = "test_agent2"
  name = "Agent 2"
  public_address = "HcSCinAe4uWs66r7pxnBn9xNcCJ5kivg5MqhvZ7rbmqbfzeg8e4Aun8ziwiersz" 
  keystore_file = "./agent2.key"

# -----------  DNAs  -----------
[[dnas]]
  id = "hello"
  file = "dist/hello_holo.dna.json"
  hash = "QmQ7XNYuiw5vxCoHoaXVsYbwS2vcPmddvNfv7SjvnaitYC"
[[instances]]
  id = "Alice"
  dna = "hello"
  agent = "test_agent1"
[instances.storage]
  type = "memory"
[[instances]]
  id = "Bob"
  dna = "hello"
  agent = "test_agent2"
[instances.storage]
  type = "memory"

[[interfaces]]
  id = "websocket_interface"
[interfaces.driver]
  type = "websocket"
  port = 3401
[[interfaces.instances]]
  id = "Alice"
[[interfaces.instances]]
  id = "Bob"
